version: "3.9"
services:
  db:
    image: postgres:16
    container_name: slater-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slater
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
